// AUTO-GENERATED by agent.js -- do not hand-edit.
// Regenerate with: node agent.js
const FACILITIES = [
  {
    "facility": "UCSF Medical Center",
    "facility_type": "academic/large-system hospital",
    "rate_used": 2704.8,
    "rate_type": "cash",
    "payer_label": "Cash / self-pay, no Cigna contract found (sum of 2 chargemaster components)",
    "deductible_portion": 2704.8,
    "coinsurance_portion": 0,
    "oop": 2704.8,
    "source_url": "https://app.box.com/index.php?rm=box_download_shared_file&shared_name=ldckxfm5nm9wah74gqi7fdhe6mrtpg5e&file_id=f_1959275070690",
    "source_label": "cash/self-pay $2,217.60 + cash/self-pay (professional component) $487.20 (summed from 2 source rows)"
  },
  {
    "facility": "California Pacific Medical Center - Van Ness Campus",
    "facility_type": "community hospital",
    "rate_used": 2849,
    "rate_type": "negotiated",
    "payer_label": "Cigna (HMO/PPO), negotiated $2,849.00",
    "deductible_portion": 2849,
    "coinsurance_portion": 0,
    "oop": 2849,
    "source_url": "https://edge.sitecorecloud.io/sutterhealt962c-sutterhealt8fce-production57cc-4860/media/Project/SutterHealth/SutterHealth/Files/billing-insurance/costs-and-charges/940562680-1740348929_california-pacific-medical-center-van-ness-campus_standardcharges.csv",
    "source_label": "CSV row 25464: code|1=72148 (HCPCS), payer_name='Cigna', plan_name='Hmo/Ppo', standard_..."
  },
  {
    "facility": "Saint Francis Memorial Hospital",
    "facility_type": "hospital-affiliated outpatient imaging",
    "rate_used": 4935,
    "rate_type": "negotiated",
    "payer_label": "Cigna (Commercial | All Other Plans), negotiated $4,935.00",
    "deductible_portion": 3000,
    "coinsurance_portion": 387,
    "oop": 3387,
    "source_url": "https://app.box.com/index.php?rm=box_download_shared_file&shared_name=8wogrqzbbev45c7pup8v9298ul2ymlpr&file_id=f_1732346032300",
    "source_label": "standard_charge_information item description='MR L SPINE WO CON' (CPT 72148), setting=o..."
  },
  {
    "facility": "SimonMed Imaging - San Francisco - Sfmrc",
    "facility_type": "freestanding imaging center",
    "rate_used": 586,
    "rate_type": "cash",
    "payer_label": "Cash / self-pay, no Cigna contract found",
    "deductible_portion": 586,
    "coinsurance_portion": 0,
    "oop": 586,
    "source_url": "https://www.mdsave.com/p/simonmed-imaging-san-francisco-sfmrc-imaging-and-radiology/mri-without-contrast/d584ffce63dc",
    "source_label": "MDsave product page, observed 2026-07-18: 'Upfront Cash Price: $586' for 'MRI without C..."
  }
];
